name: Publish Package
on:
  release:
    types: [published]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - run: go test ./...
      - run:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${github.ref_name}
      - run: GOPROXY=proxy.golang.org go list -m github.com/colemalphrus/seamux@${{ github.ref_name }}