name: Publish Package
on:
  release:
    types: [published]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.15

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  Publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo ${{github.ref_name}}
      - run: GOPROXY=proxy.golang.org go list -m github.com/colemalphrus/seamux@${{ github.ref_name }}